name: Build NutroVerify.Api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x' # Adjust this to your .NET version

    - name: Restore dependencies
      run: dotnet restore ./NutriVerify.Api/NutriVerify.Api.csproj

    - name: Build
      run: dotnet build --configuration Release ./NutriVerify.Api/NutriVerify.Api.csproj

    # - name: Run tests
    #   run: dotnet test --no-build --verbosity normal ./NutriVerify.Api.Tests/NutriVerify.Api.Tests.csproj